sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  # needed for python 3.2 tests - virtualenv>=14.0.0 dropped python 3.2 support
  # coverage>=4.0 doesn't support python 3.2 properly either
  - travis_retry pip install "virtualenv<14.0.0" tox-travis
script: tox
after_success: coveralls
